import { VerticalBox, GroupBox } from "std-widgets.slint";
import { ParameterInput } from "./parameter-input.slint";
import { FWParameters } from "../models/paramters.slint";

export component FWPreview {
    in property <FWParameters> fwp;
    in property <int> level;
    GroupBox {
        title: "\{level}级低压加热器给水参数";

        VerticalBox {
            ParameterInput {
                label: "\{level}级低压加热器给水压力p-fwi1(MPa)";
                value: fwp.p-fwxi;
                enabled: false;
            }

            ParameterInput {
                label: "\{level}级低压加热器给水比焓h-fw1i(kJ/kg)";
                value: fwp.h-fwxi;
                enabled: false;
            }

            ParameterInput {
                label: "\{level}级低压加热器给水温度T-fw1i(°C)";
                value: fwp.t-fwxi;
                enabled: false;
            }

            ParameterInput {
                label: "\{level}级低压加热器给水压力p-fw1o(MPa)";
                value: fwp.p-fwxo;
                enabled: false;
            }

            ParameterInput {
                label: "\{level}级低压加热器给水比焓h-fw1o(kJ/kg)";
                value: fwp.h-fwxo;
                enabled: false;
            }

            ParameterInput {
                label: "\{level}级低压加热器给水温度T-fw1o(°C)";
                value: fwp.t-fwxo;
                enabled: false;
            }

            ParameterInput {
                label: "\{level}级低压加热器疏水温度T-ro1k(°C)";
                value: fwp.t-roxk;
                enabled: false;
            }

            ParameterInput {
                label: "\{level}级低压加热器疏水比焓h-ro1k(kJ/kg)";
                value: fwp.h-roxk;
                enabled: false;
            }
        }
    }
}
