import { GroupBox, VerticalBox } from "std-widgets.slint";
import { ParameterInput } from "./parameter-input.slint";
import { HESParameters } from "../models/paramters.slint";

export component HESPreview {
    in property <HESParameters> hes;
    in property <int> level;

    GroupBox {
        title: "\{level}给水加热器抽汽参数";
        VerticalBox {
            ParameterInput {
                label: "\{level}级低压加热器抽汽压力p-hesx(MPa)";
                value: hes.p-hesx;
                enabled: false;
            }

            ParameterInput {
                label: "\{level}级低压加热器抽汽干度X-hesx";
                value: hes.x-hesx;
                enabled: false;
            }

            ParameterInput {
                label: "\{level}级低压加热器抽汽理想比焓h-hesxs(kJ/kg)";
                value: hes.h-hesxs;
                enabled: false;
            }

            ParameterInput {
                label: "\{level}级低压加热器抽汽比焓h-hesx(kJ/kg)";
                value: hes.h-hesx;
                enabled: false;
            }
        }
    }
}
