import { ParameterInput } from "./parameter-input.slint";
import { FWPreview } from "./fw-preview.slint";
import { HESPreview } from "./hes-preview.slint";
import { RHXPreview } from "./rhx-preview.slint";
import { AboutDialog } from "./about-dialog.slint";
import { Table3 } from "./table-3.slint";
import {NumericParameterInput} from "./numeric-parameter-input.slint";

export { ParameterInput, FWPreview, HESPreview, RHXPreview, AboutDialog, Table3, NumericParameterInput }

