import { HorizontalBox, LineEdit } from "std-widgets.slint";

export component NumericParameterInput {
    in-out property <string> label;
    in-out property <float> value;
    in-out property <string> placeholder;
    in-out property <bool> enabled: true;

    HorizontalBox {
        Text {
            text: root.label;
        }

        edit := LineEdit {
            enabled: root.enabled;
            placeholder-text: root.placeholder;
            input-type: InputType.number;

            text: root.value == 0 ? "" : "\{root.value}";

            edited(current-text) => {
                root.value = current-text.to-float();
            }
            min-width: 100px; // Adjust as needed
        }
    }
}
