/// 输入参数
export struct InputParameters {
    // 已知条件和给定参数
    /// 核电厂输出电功率, 给定，1000
    n_e: float,
    /// 一回路能量利用系数, 0.99 ~ 1.0
    n_1: float,
    /// 蒸汽发生器出口蒸汽干度，给定，99.75
    x_fh: float,
    /// 蒸汽发生器排污率，给定，1.05%
    zeta_d: float,
    /// 高压缸内效率，给定，82.07%
    n_hi: float,
    /// 低压缸内效率，给定，83.59%
    n_li: float,
    /// 汽轮机组机械效率，0.98 ~ 0.99
    n_m: float,
    /// 发电机效率，0.98 ~ 0.99
    n_ge: float,
    /// 新蒸汽压损，(3% ~ 7%)P_fh
    dP_fh: float,
    /// 再热蒸汽压损，dP_rh <= 10% P_hz
    dP_rh: float,
    /// 回热抽汽压损，(3% ~ 5%)P_cj
    dP_ej: float,
    /// 低压缸排汽压损，给定，5%P_cd
    dP_cd: float,
    // 流动损失
    dP_f: float,
    /// 高压给水加热器出口端差, 给定，3
    theta_hu: float,
    /// 低压给水加热器出口端差, 给定，2
    theta_lu: float,
    /// 加热器效率，0.97 ~ 0.99
    n_h: float,
    /// 给水泵效率，给定，0.58
    n_fwpp: float,
    /// 给水泵汽轮机内效率，0.78 ~ 0.82
    n_fwpti: float,
    /// 给水泵汽轮机机械效率，给定，0.90
    n_fwptm: float,
    /// 给水泵汽轮机减速器效率，给定， 0.98
    n_fwptg: float,
    /// 循环冷却水进口温度，给定，24
    T_sw1: float,
    // 确定的主要热力参数
    /// 反应堆冷却剂系统运行压力，15 ~ 16
    P_c: float,
    /// 反应堆出口冷却剂过冷度，15 ~ 20
    dT_sub: float,
    /// 反应堆进出口冷却剂温升，30 ~ 40
    dT_c: float,
    /// 蒸汽发生器饱和蒸汽压力，5.0 ~ 7.0
    P_s: float,
    /// 冷凝器中循环冷却水温升，6 ~ 8
    dT_sw: float,
    /// 冷凝器传热端差，3 ~ 10
    dT: float,
    // 高压缸排汽压力比，12 ~ 14
    dP_hz: float,
    // 再热蒸汽温度差
    T_rh2z: float,
    /// 回热级数
    Z: float,
    /// 低压给水加热器级数
    Z_l: float,
    /// 高压给水加热器级数
    Z_h: float,
    /// 给水温度系数，85 ~ 90
    dT_fw: float,
    // 核电站效率
    n_eNPP: float,
    // 给水泵出口压力, 1.15 ~ 1.25
    dP_fwpo: float,
    // 凝水泵出口压力, 3 ~ 3.2
    dP_cwp: float,
    // 假设冷凝器凝水量
    g_cd: float,
}


/// 附表三
export struct Result1 {
    /// 1.核电厂效率η_eNPP
    eta_enpp: float,
    /// 2.反应堆热功率Q_R
    q_r: float,
    /// 3.蒸汽发生器总蒸汽产量Ds
    d_s: float,
    /// 4.汽轮机高压缸耗气量G_shp
    g_shp: float,
    /// 5.汽轮机低压缸耗气量G_slp
    g_slp: float,
    /// 6.第一级再热器耗气量G_srh1
    g_srh1: float,
    /// 7.第二级再热器耗气量G_srh2
    g_srh2: float,
    /// 8.除氧器耗气量G_sdea
    g_sdea: float,
    /// 9.给水泵汽轮机耗气量G_sfwp
    g_sfwp: float,
    /// 10.给水泵给水量G_fw
    g_fw: float,
    /// 11.给水泵扬程H_fwp
    h_fwp: float,
    /// 12.1.第七级抽汽量G_hes7
    g_hes7: float,
    /// 12.2.第六级抽汽量G_hes6
    g_hes6: float,
    /// 13.1.第四级抽汽量G_les4
    g_les4: float,
    /// 13.2.第三级抽汽量G_les3
    g_les3: float,
    /// 13.3.第二级抽汽量G_les2
    g_les2: float,
    /// 13.4.第一级抽汽量G_les1
    g_les1: float,
    /// 14.凝结水量G_cd
    g_cd: float,
    /// 15.汽水分离器疏水量G_uw
    g_uw: float,
    /// 16.一级再热器加热蒸汽量G_zc1
    g_zc1: float,
    /// 17.二级再热器加热蒸汽量G_zc2
    g_zc2: float,
}

export struct FWParameters {
    /// 进口给水压力p_fwxi
    p_fwxi: float,
    /// 进口给水比焓h_fwxi
    h_fwxi: float,
    /// 进口给水温度T_fwxi
    t_fwxi: float,
    /// 出口给水压力p_fwxo
    p_fwxo: float,
    /// 出口给水比焓h_fwxo
    h_fwxo: float,
    /// 出口给水温度T_fwxo
    t_fwxo: float,
    /// 汽侧疏水温度T_roxk
    t_roxk: float,
    /// 汽侧疏水比焓h_roxk
    h_roxk: float,
}

export struct HESParameters {
    /// 抽汽压力p_hesx
    p_hesx: float,
    /// 抽汽干度X_hesx
    x_hesx: float,
    /// 抽汽理想比焓h_hesxs
    h_hesxs: float,
    /// 抽汽比焓h_hesx
    h_hesx: float,
}

export struct RHXParameters {
    /// 加热蒸汽进口压力p_rhx
    p_rhx: float,
    /// 加热蒸汽进口干度X_rhx
    x_rhx: float,
    /// 加热蒸汽进口温度T_rhx
    t_rhx: float,
    /// 加热蒸汽进口比焓h_rhx
    h_rhx: float,
    /// 再热器疏水比焓h_zsx
    h_zsx: float,
}

/// 附表一、二
export struct Result2 {
    // 附表一
    /// 1.核电厂输出功率N_e
    ne: float,
    /// 2.一回路能量利用系数η_1
    eta_1: float,
    /// 3.蒸汽发生器出口蒸汽干度X_fh
    x_fh: float,
    /// 4.蒸汽发生器排污率ξ_d
    zeta_d: float,
    /// 5.高压缸内效率η_hi
    eta_hi: float,
    /// 6.低压缸内效率η_li
    eta_li: float,
    /// 7.汽轮机组机械效率η_m
    eta_m: float,
    /// 8.发电机效率η_ge
    eta_ge: float,
    /// 9.新蒸汽压损Δp_fh
    dp_fh: float,
    /// 10.再热蒸汽压损Δp_rh
    dp_rh: float,
    /// 11.回热蒸汽压损Δp_ej
    dp_ej: float,
    /// 12.低压缸排气压损Δp_cd
    dp_cd: float,
    /// 13.高压给水加热器出口端差θ_hu
    theta_hu: float,
    /// 14.低压给水加热器出口端差θ_hu
    theta_lu: float,
    /// 15.加热器效率η_h
    eta_h: float,
    /// 16.给水泵效率η_fwpp
    eta_fwpp: float,
    /// 17.给水泵汽轮机内效率η_fwpti
    eta_fwpti: float,
    /// 18.给水泵汽轮机机械效率η_fwptm
    eta_fwptm: float,
    /// 19.给水泵汽轮机减速器效率η_fwptg
    eta_fwptg: float,
    /// 20.循环冷却水进口温度T_sw1
    t_sw1: float,
    // 附表二
    /// 1.反应堆冷却剂系统运行压力p_c
    p_c: float,
    /// 2.冷却剂压力对应的饱和温度T_cs
    t_cs: float,
    /// 3.反应堆出口冷却剂过冷度ΔT_sub
    dt_sub: float,
    /// 4.反应堆出口冷却剂温度T_co
    t_co: float,
    /// 5.反应堆进出口冷却剂温升ΔT_c
    dt_c: float,
    /// 6.反应堆进口冷却剂温度T_ci
    t_ci: float,
    /// 7.蒸汽发生器饱和蒸汽压力p_s
    p_s: float,
    /// 8.蒸汽发生器饱和蒸汽温度T_fh
    t_fh: float,
    /// 9.一、二次侧对数平均温差ΔT_m
    dt_m: float,
    /// 10.冷凝器中循环冷却水温升ΔT_sw
    dt_sw: float,
    /// 11.冷凝器传热端差δT
    dt: float,
    /// 12.冷凝器凝结水饱和温度T_cd
    t_cd: float,
    /// 13.冷凝器的运行压力p_cd
    p_cd: float,
    /// 14.高压缸进口的蒸汽压力p_hi
    p_hi: float,
    /// 15.高压缸进口蒸汽干度X_hi
    x_hi: float,
    /// 15.1.蒸汽发生器出口蒸汽比焓h_fh
    h_fh: float,
    /// 15.2.蒸汽发生器出口蒸汽比熵s_fh
    s_fh: float,
    /// 15.3.高压缸进口蒸汽比熵s_hi
    s_hi: float,
    /// 16.高压缸排气压力p_hz
    p_hz: float,
    /// 17.高压缸排气干度X_hz
    x_hz: float,
    /// 17.1.高压缸进口蒸汽比焓h_hi
    h_hi: float,
    /// 17.2.高压缸出口理想比焓h_hzs
    h_hzs: float,
    /// 17.3.高压缸出口蒸汽比焓h_hz
    h_hz: float,
    /// 18.汽水分离器进口蒸汽压力p_spi
    p_spi: float,
    /// 19.汽水分离器进口蒸汽干度X_spi
    x_spi: float,
    /// 19.1.汽水分离器出口疏水压力p_uw
    p_uw: float,
    /// 19.2.汽水分离器出口疏水比焓h_uw
    h_uw: float,
    // 第一级再热器
    /// 20.再热蒸汽进口压力p_rh1i
    p_rh1i: float,
    /// 21.再热蒸汽进口干度X_rh1i
    x_rh1i: float,
    /// 21.1.一级再热器进口蒸汽比焓h_rh1i
    h_rh1i: float,
    /// 22.加热蒸汽进口压力p_rh1hs
    p_rh1hs: float,
    /// 23.加热蒸汽进口干度X_rh1hs
    x_rh1hs: float,
    // 第二级再热器
    /// 24.再热蒸汽进口压力p_rh2i
    p_rh2i: float,
    /// 25.再热蒸汽进口温度T_rh2i
    t_rh2i: float,
    /// 26.再热蒸汽出口压力p_rh2z
    p_rh2z: float,
    /// 27.再热蒸汽出口温度T_rh2z
    t_rh2z: float,
    /// 27.1.二级再热器出口比焓h_rh2z
    h_rh2z: float,
    /// 27.2.每级再热器平均焓升Δh_rh
    dh_rh: float,
    /// 27.3.一级再热器出口蒸汽比焓h_rh1z
    h_rh1z: float,
    /// 27.4.二级再热器进口蒸汽比焓h_rh2i
    h_rh2i: float,
    /// 28.加热蒸汽进口压力p_rh2hs
    p_rh2hs: float,
    /// 29.加热蒸汽进口干度X_rh2hs
    x_rh2hs: float,
    // 低压缸
    /// 30.进口蒸汽压力p_li
    p_li: float,
    /// 31.进口蒸汽温度T_li
    t_li: float,
    /// 32.排汽压力p_lz
    p_lz: float,
    /// 33.排汽干度X_lz
    x_lz: float,
    /// 33.1.低压缸进口蒸汽比熵s_li
    s_li: float,
    /// 33.2.低压缸进口蒸汽比焓h_li
    h_li: float,
    /// 33.3.低压缸出口理想比焓h_lzs
    h_lzs: float,
    /// 33.4.低压缸出口蒸汽比焓h_lz
    h_lz: float,
    /// 34.回热级数Z
    z: float,
    /// 35.低压给水加热器级数Z_l
    z_l: float,
    /// 36.高压给水加热器级数Z_h
    z_h: float,
    /// 37.第一次给水回热分配Δh_fw
    dh_fw: float,
    /// 37.1.蒸汽发生器运行压力饱和水比焓h_s
    h_s: float,
    /// 37.2.冷凝器出口凝结水比焓h_cd
    h_cd: float,
    /// 37.3.每级加热器理论给水焓升Δh_fwop
    dh_fwop: float,
    /// 37.4.最佳给水比焓h_fwop
    h_fwop: float,
    /// 37.5.最佳给水温度T_fwop
    t_fwop: float,
    /// 37.6.实际给水温度T_fw
    t_fw: float,
    /// 37.7.实际给水比焓h_fw
    h_fw: float,
    /// 38.高压加热器给水焓升Δh_fwh
    dh_fwh: float,
    /// 38.1.除氧器运行压力p_dea
    p_dea: float,
    /// 38.2.除氧器出口饱和水比焓h_deao
    h_deao: float,
    /// 39.除氧器及低压加热器给水焓升Δh_fwl
    dh_fwl: float,
    /// 39.1.凝水泵出口给水压力p_cwp
    p_cwp: float,
    /// 39.2.凝水泵出口给水比焓h_cwp
    h_cwp: float,
    /// 39.3.凝水泵出口至除氧器出口的阻力压降Δp_cws
    dp_cws: float,
    /// 39.4.每级低压加热器及除氧器的阻力压降Δp_fi
    dp_fi: float,
    /// 40.低压加热器给水参数(1 ~ 4级)
    lfwx: [FWParameters],
    /// 41.进口给水比焓h_deai
    h_deai: float,
    /// 42.出口给水比焓h_deao
    h_deao1: float,
    /// 43.出口给水温度T_dea
    t_dea: float,
    /// 44.运行压力p_dea
    p_dea1: float,
    /// 44.1.给水泵出口压力p_fwpo
    p_fwpo: float,
    /// 44.2.给水泵出口流体比焓h_fwpo
    h_fwpo: float,
    /// 44.3.蒸汽发生器进口给水压力p_fwi
    p_fwi: float,
    /// 45.高压加热器给水参数(6 ~ 7级)
    hfwx: [FWParameters],
    // 46.高压缸抽汽
    /// 46.1.高压缸进口蒸汽比熵s_hi
    s_hi1: float,
    /// 46.2.高压缸进口蒸汽比焓h_hi
    h_hi1: float,
    /// 第六、七级给水加热器抽汽参数
    hhes: [HESParameters],
    // 47.低压缸抽汽
    /// 47.1.低压缸进口蒸汽比熵s_li
    s_li1: float,
    /// 47.2.低压缸进口蒸汽比焓h_li
    h_li1: float,
    /// 第一至四级给水加热器抽汽参数
    lhes: [HESParameters],
    /// 48.再热器抽汽(第一、二级再热器抽汽参数)
    rhx: [RHXParameters],
}

export struct MyResult {
    /// 热平衡计算结果
    result1: [Result1],
    /// 附表
    result2: Result2,
}
